apiVersion: skaffold/v1
kind: Config

metadata:
  name: edsc-self-service-portal

build:
  artifacts:
    - image: farberg/edsc-self-service-portal
      context: .
      docker:
        dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
      - config/k8s-deployment.yaml

profiles:
  - name: Development Profile
    activation:
      - command: dev
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: Dockerfile.dev
