apiVersion: apps/v1
kind: Deployment
metadata:
  name: edsc-self-service-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "edsc-self-service-portal"
  template:
    metadata:
      labels:
        app: "edsc-self-service-portal"
    spec:
      containers:
        - name: edsc-self-service-portal
          image: farberg/edsc-self-service-portal
          args:
            - "--mode"
            - "production"
            - "--verbose"
          ports:
            - containerPort: 8080
#          livenessProbe:
#            httpGet:
#              path: /health/liveness
#              port: 7777
#            initialDelaySeconds: 5
#            periodSeconds: 30
#          readinessProbe:
#            httpGet:
#              path: /health/readiness
#              port: 7777
#            initialDelaySeconds: 5
#            periodSeconds: 30
#          resources:
#            limits:
#              cpu: ".1"
#              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: edsc-self-service-portal-web-service
spec:
  selector:
    app: "edsc-self-service-portal"
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: edsc-self-service-portal-ingress
  annotations:
    external-dns.alpha.kubernetes.io/hostname: edsc-portal.edsc.farberg.de
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - "edsc-portal.edsc.farberg.de"
  rules:
    - host: edsc-portal.edsc.farberg.de
      http:
        paths:
          - path: /
            backend:
              serviceName: edsc-self-service-portal-web-service
              servicePort: 8080
